TeamSnuggie/FEC

.gitignore
feat: Created a shared components directory inside the source folder
=> Create shared components directory

client/dist/bundle.js, client/src/Components/QuestionsAndAnswers/Form/SearchQuestions.jsx, client/src/Components/QuestionsAndAnswers/QnaIndex.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/AddAnswer.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/AddQuestion.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/IndividualQuestions.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/MoreAnsweredQuestions.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/QuestionsList.jsx, client/src/Components/QuestionsAndAnswers/addModal.jsx, client/src/Components/QuestionsAndAnswers/addQuestion.jsx, client/src/Components/QuestionsAndAnswers/individualQuestions.jsx, client/src/Components/QuestionsAndAnswers/moreAnsweredQuestions.jsx, client/src/Components/QuestionsAndAnswers/questionsList.jsx, client/src/Components/QuestionsAndAnswers/searchQuestions.jsx, client/src/index.js
feat: Reorganized the folders within the Q&A section and created an individual Index. Also started a rough draft of how each component are laid out: Form, Question List, The Modal Buttons.
=> Complete Rough Draft of the Q&A Folder Structure/Components

.babelrc, client/src/Components/ProductOverview/StyledComponents/Containers.jsx
feat: initialized styled components directory and file for Product Overview
also minor bugfix: add babel plugin for styled components to babel config file
Please review and merge, time permitting
=> initialized styled components file for Product Overview

client/src/Components/ProductOverview/ImageGallery/Gallery.jsx, client/src/Components/ProductOverview/Overview.jsx, client/src/Components/ProductOverview/ProductInformation/AddToCart.jsx, client/src/Components/ProductOverview/ProductInformation/Information.jsx, client/src/Components/ProductOverview/ProductInformation/OverviewStarRating.jsx, client/src/Components/ProductOverview/ProductInformation/StyleSelector.jsx, client/src/Components/ProductOverview/StyledComponents/Containers.jsx, client/src/Components/ProductOverview/StyledComponents/ImageGallery/ImageThumbnails.jsx, client/src/Components/ProductOverview/StyledComponents/ImageGallery/MainImage.jsx, client/src/Components/ProductOverview/StyledComponents/ProductInformation/AddToCart/AddToCart.jsx, client/src/Components/ProductOverview/StyledComponents/ProductInformation/AddToCart/Favorite.jsx, client/src/Components/ProductOverview/StyledComponents/ProductInformation/AddToCart/QuantityDropdown.jsx, client/src/Components/ProductOverview/StyledComponents/ProductInformation/AddToCart/SizeDropdown.jsx, client/src/Components/ProductOverview/StyledComponents/ProductInformation/OverviewStars.jsx, client/src/Components/ProductOverview/StyledComponents/ProductInformation/StyleThumbnail.jsx
I've laid out the basic structure for all of the components within the Product Information widget. I've applied some styling, but most if not all of it is placeholder styling-- to be done after the functionality of the widget is complete.
=> feat: create styled structure for Product Information widget

client/src/Components/ProductOverview/Overview.jsx, server/helpers/HR_API.jsx, server/routes.js, server/server.js
I have implemented the following server-side features:
- Create a helpers directory and inside is HR_API.jsx, which contains helper functions that interface with Hack Reactor's API to get relevant data (so far, only products and their styles)
- Configure server/routes.js to handle requests (so far, only getting products, either specific or all, and styles)
Please review and merge; with this you should be able to configure your widgets on the client side to send requests to the server and work with the data received.
=> feat: implement server-side request handling

client/src/Components/RelatedItemsAndComparison/Add.jsx, client/src/Components/RelatedItemsAndComparison/Cards.jsx, client/src/Components/RelatedItemsAndComparison/Carousel.jsx, client/src/Components/RelatedItemsAndComparison/ComparisonModal.jsx, client/src/Components/RelatedItemsAndComparison/OutfitList.jsx, client/src/Components/RelatedItemsAndComparison/RInCIndex.jsx, client/src/Components/RelatedItemsAndComparison/RelatedItemsList.jsx, client/src/index.js, package-lock.json, server/helpers/HR_API.jsx, server/routes.js, webpack.config.js
Added api calls in related items folder and methods in routes/ helpers
@Panlord @dondo5252 @justjjasper
For review and approval
=> feat: added api calls and methods

client/src/Components/QuestionsAndAnswers/QnaIndex.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/AnswerList.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/IndividualAnswer.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/IndividualQuestions.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/QuestionsList.jsx, client/src/Components/QuestionsAndAnswers/StyledComponents/Containers.jsx, client/src/Components/QuestionsAndAnswers/StyledComponents/QuestionWithAnswers/QnAList.jsx, package-lock.json, server/helpers/HR_API.jsx, server/routes.js
feat: Added API helper functions and made routes for the QnA
feat: Fetched data from the server and implemented them into each question 
feat: Initialized the question state in the QnAIndex
refactor: Added an additional params to the API Helper function in order to display a certain amount of questions at a time
=> Create Helper Funcs and Flushed Data into the QnA Index

client/src/Components/ProductOverview/ImageGallery/Gallery.jsx, client/src/Components/ProductOverview/ImageGallery/MainImage.jsx, client/src/Components/ProductOverview/ImageGallery/Thumbnail.jsx, client/src/Components/ProductOverview/ImageGallery/ThumbnailList.jsx, client/src/Components/ProductOverview/StyledComponents/ImageGallery/ImageThumbnails.jsx, client/src/Components/ProductOverview/StyledComponents/ImageGallery/MainImage.jsx
Implement various features and styles as described in the commits. 
Tl;dr:
- feat: clicking on image thumbnails changes the main image displayed
- style: visual indicator attached to the image thumbnail being displayed as the main image
- feat: clicking on the conditionally rendered left/right arrows on the sides of the main image changes the displayed main image accordingly
- style: hovering over the arrow buttons or main image changes the mouse cursor accordingly
Please feel free to point out any optimizations/adjustments that could be made (there are plenty), but take into account that achieving MVP requirements is the main goal at this point in time.
=> feat: implement Image Gallery functionality

client/src/Components/ProductOverview/StyledComponents/ImageGallery/ImageThumbnails.jsx, client/src/Components/ProductOverview/StyledComponents/ProductInformation/StyleThumbnail.jsx
also small styling adjustments to style thumbnails
=> style: change mouse cursor when hovering over image and style thumbnails

client/src/Components/RatingsAndReviews/ReviewList/ReviewTiles.jsx, client/src/Components/RatingsAndReviews/StyledComponents/ReviewLimitScroll.jsx, client/src/Components/RatingsAndReviews/StyledComponents/ReviewTile.jsx
feat: styled Review Tiles
styled review tiles in reviewsTile.jsx
type: style
=> Reviews list

client/src/Components/QuestionsAndAnswers/QnaIndex.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/AddAnswer.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/AnswerList.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/IndividualAnswer.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/IndividualQuestions.jsx, client/src/Components/QuestionsAndAnswers/QuestionWithAnswers/QuestionsList.jsx, server/helpers/HR_API.jsx, server/routes.js
Implemented an AnswerModal thats missing an image upload functionality, fixed a POST and PUT request bug from the server side when using the API Helper functions, added css styling when hovering over upvotes.
=> tldr: Added AnswerModal and Fixed Previous Bugs

client/src/App.js, client/src/Components/QuestionsAndAnswers/QnaIndex.jsx
A small PR. An option to refactor useContext to pass down multiple values in the future is possible
=> feat: implement a useContext within App.js

client/src/App.js, client/src/Components/RelatedItemsAndComparison/RInCIndex.jsx, client/src/Components/RelatedItemsAndComparison/RelatedCards.jsx, client/src/Components/RelatedItemsAndComparison/RelatedItemsList.jsx
for you guys to have an easier time testing your components
=> feat: added changing app state product id on card click

client/src/Components/ProductOverview/Overview.jsx, client/src/Components/ProductOverview/ShareButtons.jsx, client/src/Components/ProductOverview/StyledComponents/Containers.jsx, client/src/Components/ProductOverview/StyledComponents/ProductInformation/Description.jsx
also add feature: Share buttons next to the product's features; they link to Facebook, Twitter, and Pinterest respectively
=> feat: conditionally render product slogan/description below Product Overview widget

client/src/Components/RelatedItemsAndComparison/ComparisonModal.jsx, client/src/Components/RelatedItemsAndComparison/OutfitCards.jsx, client/src/Components/RelatedItemsAndComparison/OutfitCarousel.jsx, client/src/Components/RelatedItemsAndComparison/OutfitList.jsx, client/src/Components/RelatedItemsAndComparison/RInCIndex.jsx, client/src/Components/RelatedItemsAndComparison/RelatedCards.jsx, client/src/Components/RelatedItemsAndComparison/RelatedCarousel.jsx, client/src/Components/RelatedItemsAndComparison/RelatedItemsList.jsx
@Panlord @dondo5252 @justjjasper  For review
=> feat: implemented carousel fwd and back

client/src/Components/ProductOverview/Overview.jsx, client/src/Components/ProductOverview/ProductInformation/Information.jsx, client/src/Components/ProductOverview/ShareButtons.jsx
Various bugfixes implemented. These bugs did not hinder website functionality to great extent.
- bugfix: FeatureList in Overview slogan/description now has keys
- bugfix: class changed to className
- bugfix: charset changed to charSet in share buttons
=> various bugfixes regarding classname and charset

client/src/App.js, client/src/Components/ProductOverview/ProductInformation/AddToCart.jsx, client/src/Components/ProductOverview/ProductInformation/Information.jsx, server/helpers/HR_API.jsx, server/routes.js
This intends to implement Add To Cart button functionality by doing the following:
- feat: add server route and API helper function for adding product to cart (POST request)
- refactor: remove unnecessary console logs and elements not needed as per Business Requirements Document
- feat: implement Size selector dropdown
The size dropdown renders dynamically based on selected product style.
- feat: implement quantity selector dropdown
The quantity dropdown renders dynamically based on selected style size.
- feat: implement Add To Cart button functionality
Clicking button without selected size and/or quantity conditionally renders messages. Clicking with valid selected size and quantity adds item (size and quantity) to cart.
Many optimizations and much refactoring can be done to improve this …
=> feat: implement Add To Cart component functionality

test/Ratings&Reviews/OverallBreakdown.test.js, test/Ratings&Reviews/ReviewList.test.js, test/Ratings&Reviews/ReviewTile.test.js
implemented test for Ratings and Reviews
type: test
=> feat:tests

client/src/Components/ProductOverview/StyledComponents/Containers.jsx
style: resize product overview description container width to match Product Overview width
=> style: fix Product Overview Description sizing

client/src/App.js, client/src/Components/ProductOverview/Overview.jsx, client/src/Components/ProductOverview/ProductInformation/AddToCart.jsx, client/src/Components/ProductOverview/ProductInformation/Information.jsx, client/src/Components/ProductOverview/ProductInformation/OverviewStarRating.jsx, client/src/Components/SharedComponents/StarRating.jsx
I have done the following in an effort to match the Business Requirements Document more closely and be more consistent in displayed data across the app:
- bugfix: sale price properly conditionally renders
- refactor: default selected quantity becomes 1 when a size is selected
- refactor: App.js GET requests the API for review data whenever a specific product is selected
- refactor: review data retrieved from App.js passed down as a prop among Product Overview widget's components
- refactor: Star Rating shared component refactored to calculate average rating from raw review data passed down to it as a prop; **since this shared component's prop expectations have changed (from expecting review metadata to expecting an array of review objects), anyone using this shared component needs to …
=> bugfixes and refactoring: Product Overview widget, App.js, and Star Rating shared component

client/src/Components/RatingsAndReviews/OverallBreakDown/OverallBreakdown.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviewsIndex.jsx, client/src/Components/RatingsAndReviews/ReviewList/AddReviewModal.jsx, client/src/Components/RatingsAndReviews/ReviewList/ReviewList.jsx, client/src/Components/RatingsAndReviews/ReviewList/ReviewTiles.jsx, client/src/Components/RatingsAndReviews/ReviewList/StarRatingReviewModal.jsx, client/src/Components/RatingsAndReviews/StyledComponents/AddReviewModal.jsx, client/src/Components/RatingsAndReviews/StyledComponents/BreakdownBars.jsx, client/src/Components/RatingsAndReviews/StyledComponents/R&RContainer.jsx, client/src/Components/RatingsAndReviews/StyledComponents/ReviewLimitScroll.jsx, client/src/Components/RatingsAndReviews/StyledComponents/ReviewListStyle.jsx, client/src/Components/RatingsAndReviews/StyledComponents/ReviewTile.jsx
=> CSS Reviews

client/src/App.js, client/src/Components/ProductOverview/ProductInformation/AddToCart.jsx, client/src/Components/RelatedItemsAndComparison/OutfitList.jsx, client/src/Components/RelatedItemsAndComparison/RInCIndex.jsx, client/src/Components/RelatedItemsAndComparison/RelatedItemsList.jsx, server/routes.js
Applied the following to the div at which the App (which houses all of the widgets) is rendered on:
- centered all widgets by using: flex --> flex-direction row --> align-items center
- applied background-color to be light-primary color from color palette (the light shade of green #828e82)
Please pull this branch to your local machine by doing `git fetch origin AppContainerStyling` and then `git checkout AppContainerStyling` to see these changes in your local machine and review before responding to the pull request. Honest feedback on the look of this will be taken into account and appreciated.
=> style: App container styling

client/src/Components/RatingsAndReviews/ReviewList/AddReviewModal.jsx, client/src/Components/RatingsAndReviews/StyledComponents/AddReviewModal.jsx, client/src/Components/RatingsAndReviews/StyledComponents/BreakdownBars.jsx, client/src/Components/RatingsAndReviews/StyledComponents/R&RContainer.jsx
=> CSS styling

client/src/Components/RatingsAndReviews/StyledComponents/AddReviewModal.jsx
@dondo5252 Please take a look if these were the intended changes that you wanted
=> style: fix Add Review modal style
